In [1]:
import pandas as pd
import re

In [2]:
#load the data
df = pd.read_csv("../../data/data.csv")

In [3]:
df.head()

,index,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors
0,0,Sr Data Scientist,$137K-$171K (Glassdoor est.),Description\n\nThe Senior Data Scientist is re...,3.1,Healthfirst\n3.1,"New York, NY","New York, NY",1001 to 5000 employees,1993,Nonprofit Organization,Insurance Carriers,Insurance,Unknown / Non-Applicable,"EmblemHealth, UnitedHealth Group, Aetna"
1,1,Data Scientist,$137K-$171K (Glassdoor est.),"Secure our Nation, Ignite your Future\n\nJoin ...",4.2,ManTech\n4.2,"Chantilly, VA","Herndon, VA",5001 to 10000 employees,1968,Company - Public,Research & Development,Business Services,$1 to $2 billion (USD),-1
2,2,Data Scientist,$137K-$171K (Glassdoor est.),Overview\n\n\nAnalysis Group is one of the lar...,3.8,Analysis Group\n3.8,"Boston, MA","Boston, MA",1001 to 5000 employees,1981,Private Practice / Firm,Consulting,Business Services,$100 to $500 million (USD),-1
3,3,Data Scientist,$137K-$171K (Glassdoor est.),JOB DESCRIPTION:\n\nDo you have a passion for ...,3.5,INFICON\n3.5,"Newton, MA","Bad Ragaz, Switzerland",501 to 1000 employees,2000,Company - Public,Electrical & Electronic Manufacturing,Manufacturing,$100 to $500 million (USD),"MKS Instruments, Pfeiffer Vacuum, Agilent Tech..."
4,4,Data Scientist,$137K-$171K (Glassdoor est.),Data Scientist\nAffinity Solutions / Marketing...,2.9,Affinity Solutions\n2.9,"New York, NY","New York, NY",51 to 200 employees,1998,Company - Private,Advertising & Marketing,Business Services,Unknown / Non-Applicable,"Commerce Signals, Cardlytics, Yodlee"

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 672 entries, 0 to 671
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   index              672 non-null    int64
 1   Job Title          672 non-null    str
 2   Salary Estimate    672 non-null    str
 3   Job Description    672 non-null    str
 4   Rating             672 non-null    float64
 5   Company Name       672 non-null    str
 6   Location           672 non-null    str
 7   Headquarters       672 non-null    str
 8   Size               672 non-null    str
 9   Founded            672 non-null    int64
 10  Type of ownership  672 non-null    str
 11  Industry           672 non-null    str
 12  Sector             672 non-null    str
 13  Revenue            672 non-null    str
 14  Competitors        672 non-null    str
dtypes: float64(1), int64(2), str(12)
memory usage: 78.9 KB

In [5]:
df.describe(include='all')

,index,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors
count,672.000000,672,672,672,672.000000,672,672,672,672,672.000000,672,672,672,672,672
unique,NaN,172,30,489,NaN,432,207,229,9,NaN,13,58,23,14,108
top,NaN,Data Scientist,$75K-$131K (Glassdoor est.),Job Overview: The Data Scientist is a key memb...,NaN,Maxar Technologies\n3.5,"San Francisco, CA","New York, NY",51 to 200 employees,NaN,Company - Private,-1,Information Technology,Unknown / Non-Applicable,-1
freq,NaN,337,32,12,NaN,12,69,33,135,NaN,397,71,188,213,501
mean,335.500000,NaN,NaN,NaN,3.518601,NaN,NaN,NaN,NaN,1635.529762,NaN,NaN,NaN,NaN,NaN
std,194.133974,NaN,NaN,NaN,1.410329,NaN,NaN,NaN,NaN,756.746640,NaN,NaN,NaN,NaN,NaN
min,0.000000,NaN,NaN,NaN,-1.000000,NaN,NaN,NaN,NaN,-1.000000,NaN,NaN,NaN,NaN,NaN
25%,167.750000,NaN,NaN,NaN,3.300000,NaN,NaN,NaN,NaN,1917.750000,NaN,NaN,NaN,NaN,NaN
50%,335.500000,NaN,NaN,NaN,3.800000,NaN,NaN,NaN,NaN,1995.000000,NaN,NaN,NaN,NaN,NaN
75%,503.250000,NaN,NaN,NaN,4.300000,NaN,NaN,NaN,NaN,2009.000000,NaN,NaN,NaN,NaN,NaN
max,671.000000,NaN,NaN,NaN,5.000000,NaN,NaN,NaN,NaN,2019.000000,NaN,NaN,NaN,NaN,NaN

In [6]:
df.isnull().sum()

index                0
Job Title            0
Salary Estimate      0
Job Description      0
Rating               0
Company Name         0
Location             0
Headquarters         0
Size                 0
Founded              0
Type of ownership    0
Industry             0
Sector               0
Revenue              0
Competitors          0
dtype: int64

In [7]:
#examine Salary Estimate column
print(df['Salary Estimate'].value_counts().head(10))

Salary Estimate
$75K-$131K (Glassdoor est.)     32
$79K-$131K (Glassdoor est.)     32
$99K-$132K (Glassdoor est.)     32
$137K-$171K (Glassdoor est.)    30
$90K-$109K (Glassdoor est.)     30
$56K-$97K (Glassdoor est.)      22
$79K-$106K (Glassdoor est.)     22
$90K-$124K (Glassdoor est.)     22
$101K-$165K (Glassdoor est.)    21
$91K-$150K (Glassdoor est.)     21
Name: count, dtype: int64

In [8]:
#clean text columns
df['Job Title'] = df['Job Title'].str.strip().str.lower()
df['Job Description'] = df['Job Description'].str.strip().str.lower()
df['Job Description'] = df['Job Description'].str.replace('\n', ' ', regex=True)
df['Job Description'] = df['Job Description'].str.replace('\s+', ' ', regex=True)
#standardize text for NLP or DB ingestion.

In [9]:
#extract numeric salary
#remove $ and K, extract min and max
salary_range = df['Salary Estimate'].str.extract(r'\$?(\d+)K?-\$?(\d+)K?')
df['salary_min'] = salary_range[0].astype(float)
df['salary_max'] = salary_range[1].astype(float)
df['salary_avg'] = (df['salary_min'] + df['salary_max']) / 2

In [ ]:
# keep useful columns for ML
df_cleaned = df[
    [
        'Job Title',
        'Job Description',
        'Rating',
        'Location',
        'Size',
        'Industry',
        'Sector',
        'Founded',
        'salary_avg'
    ]
]
# Rename columns
df_cleaned.columns = [
    'job_title',
    'job_description',
    'rating',
    'location',
    'size',
    'industry',
    'sector',
    'founded',
    'salary_avg'
]

In [ ]:
#save
df_cleaned.to_csv("../../data/data_cleaned.csv", index=False)

In [ ]:
#check
df_cleaned.head()
df_cleaned.info()

<class 'pandas.DataFrame'>
RangeIndex: 672 entries, 0 to 671
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   job_title        672 non-null    str
 1   job_description  672 non-null    str
 2   rating           672 non-null    float64
 3   location         672 non-null    str
 4   size             672 non-null    str
 5   industry         672 non-null    str
 6   sector           672 non-null    str
 7   founded          672 non-null    int64
 8   salary_avg       672 non-null    float64
dtypes: float64(2), int64(1), str(6)
memory usage: 47.4 KB